### ISSUE TITLE
Compile list of Appalachia counties

### ISSUE THREAD

**Issue by akanik** [davemistich/election-appalachia#1]
In a CSV. With FIPS if possible.

**Comment by mkiang** [comment]
Any chance this is publicly available? Would like to avoid reproducing work if possible. Will address #4 in exchange for making the file public.

**Comment by akanik** [comment]
Hey @mkiang I'm attaching it here. I'll try and get it integrated into this repo as well.

[appal-counties-geoid.csv.zip](https://github.com/davemistich/election-appalachia/files/1478859/appal-counties-geoid.csv.zip)

Issue #4 should be pretty easy to satisfy with the `geoid` column now present in the csv. Let me know if you have any issues.

**Comment by mkiang** [comment]
@akanik, thanks. If you have no objections, I've added the data to my `R` package with attribution to this repo. See https://github.com/mkiang/narcan/commit/7f8153f592fcfaf58c464d32732c0bfb9f93f729 and [the reference page](https://mkiang.github.io/narcan/reference/appalachia_fips.html)

I can subset the shapefile. Do you have a preference for which file? I'm currently using the 2010 Census cartographic boundary file at 1:20m resolution. I can subset that and provide you with code if you want to subset a different file?
